version: '3.8'

services:
  web:
    image: mymovie-api:1.0.0
    build: .
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  dbdata: